### ISSUE TITLE
Code Blocks are broken and prevent the page from rendering

### ISSUE THREAD

**Issue by nexeh** [Dynalon/mdwiki#207] opened 2015-03-27 17:53 UTC
I have noticed months ago that when i pulled the latest mdwiki that some of my pages stopped working. i ended up rolling it back at the time. Now that i have been contributing to the project with the chart gimmick i rolled at our to my internal site and i have pages that are completely broken. I have taken the time to narrow down the problem to code blocks.

This line introduces the issue:

    ```xml
    <property name="org.apache.cxf.logging.enabled" value="true"/>
    ```

It seems like that if i provide no language or 'no-highlight' everything works fine. otherwise i see the following:

    "[FATAL] Timeout reached for done callback in stage: gimmick. Did you forget a done() call in a .subscribe() ?" index.html:198:13673
    "[FATAL] stage gimmick failed running subscribed function: function (a){b(),a()}"
    A script on this page may be busy, or it may have stopped responding. You can stop the script now,     open the script in the debugger, or let the script continue.

    Script: file:///C:/My/Path/index.html#!PageName.md:118

**Comment by nexeh** [comment] 2015-03-27 18:20
Is this related to Issue #39 ? I was just reading that and it seems to be an infinite loop much like what was talked about in that issue. Granted, i didnt read the entire chain

**Comment by Dynalon** [comment] 2015-03-28 08:45
This is pretty much a duplicate of #39. In master, I replaced highlight.js with prism.js. Me and other people have tried to fnid the cause of the infinite loop in highlight but eventually gave up. See the comments on #39 for details.

The problem ist, porting prism.js back to 0.6.x would break the API for users that upgrade. But since this is a very important and often requested feature/fix, I am thinking if I shall create a  config switch that will use prism.js in 0.6.x to prevent incompatibility

**Closed by Dynalon** 2015-03-28 08:45 UTC
