### ISSUE TITLE
Pages Hangs on Code block

### ISSUE THREAD

**Issue by volnet** [Dynalon/mdwiki#274] opened 2016-03-26 17:56 UTC
I am trying to use the code block like this:

```

     ```xml
     <item/>
     ```

```

The page would be hung. I have to remove the xml tag like this:


```

     ```
     <item/>
     ```

```

**Comment by Dynalon** [comment] 2016-03-26 20:43
duplicate of #39

**Closed by Dynalon** 2016-03-26 20:43 UTC

**Comment by volnet** [comment] 2016-04-10 10:35
thanks you
