### ISSUE TITLE
Implement search

### ISSUE THREAD

**Issue by ChristianAE** [Dynalon/mdwiki#267] opened 2016-02-29 10:37 UTC
I recently started using MDWiki. The fact that I just commit the .html file and have the same wiki everywhere without the need for any kind of hosting is as good as it gets for me!
The only thing I'm missing is to be able to search my wiki.

Is there a plan to implement some kind of search functionality? Or is there a fork which added a search? Is anyone aware of a workaround to cope with it?

**Comment by Dynalon** [comment] 2016-02-29 12:21
duplicate of #45

**Closed by Dynalon** 2016-02-29 12:21 UTC
