### ISSUE TITLE
Page hangs when I change language for syntax highlighting

### ISSUE THREAD

**Issue by neman** [Dynalon/mdwiki#224] opened 2015-07-15 12:05 UTC
You can reproduce this bug with mdwiki example on page http://dynalon.github.io/mdwiki/#!quickstart.md.

I cloned the example from github repo https://github.com/Dynalon/mdwiki/tree/gh-pages
I changed language from javascript to csharp and page hangs.

`javascript`
```javascript
var hello = function () {
    // say hello
    alert('Hello world!');
}
```

`csharp`
```csharp
var hello = function () {
    // say hello
    alert('Hello world!');
}
```

**Comment by Dynalon** [comment] 2015-07-15 12:10
duplicate of #39

**Closed by Dynalon** 2015-07-15 12:10 UTC
