### ISSUE TITLE
Navigation dropdown needs dropdowns at multiple levels of depth

### ISSUE THREAD

**Issue by tjyothsna16** [Dynalon/mdwiki#326] opened 2017-06-21 19:22 UTC
I see that navigation bar supports only one level of dropdown menu. It would be great to have multiple levels of dropdown menu.

**Comment by Dynalon** [comment] 2017-06-21 20:33
This is a duplicate of #250. Short answer is: Multiple levels of nesting do not work well on small devices (tables, phones) which is the reason bootstrap never implemented it, and so do I see it for mdwiki.

**Closed by Dynalon** 2017-06-21 20:33 UTC
