### ISSUE TITLE
how to put mavigation bar to center

### ISSUE THREAD

**Issue by wupeng1988** [Dynalon/mdwiki#305] opened 2016-12-18 14:03 UTC
Sorry for my poor English, I mean how to make the navbar like  `align:center`, not `align: left`.  Just like mkdocs menu bar.

**Comment by Dynalon** [comment] 2017-03-30 18:03
this feature is currently not implemented. as this is not a bug, i'm closing this.

**Closed by Dynalon** 2017-03-30 18:03 UTC
