### ISSUE TITLE
mdwiki CPU spike to 100% when lang for highlight isn't in list

### ISSUE THREAD

**Issue by rdavidso** [Dynalon/mdwiki#262] opened 2016-02-17 19:47 UTC
If the lang string in:
```javascript
    function highlight () {
        // marked adds lang-ruby, lang-csharp etc to the <code> block like in GFM
        var $codeblocks = $('pre code[class^=lang-]');
        return $codeblocks.each(function() {
            var $this = $(this);
            var classes = $this.attr('class');
            // TODO check for other classes and only find the lang- one
            // highlight doesnt want a lang- prefix
            var lang = classes.substring(5);
            $this.removeClass(classes);
            $this.addClass(lang);
            var x = hljs.highlightBlock($this[0]);
        });
    }
```
Is say, `undefined` or `asdf`, the `hljs.highlightBlock()` function spins forever with google chrome reporting the page's usage at 100%.

**Comment by Dynalon** [comment] 2016-02-18 08:42
duplicate of #39

**Closed by Dynalon** 2016-02-18 08:42 UTC
