### ISSUE TITLE
Pagination support?

### ISSUE THREAD

**Issue by MasterGroosha** [Dynalon/mdwiki#313] opened 2017-03-06 23:01 UTC
I tried to copy pagination/pager code from http://bootswatch.com/flatly/#navs, however, buttons are positioned vertically rather then horizontally. Can this be fixed?

![image](https://cloud.githubusercontent.com/assets/2780044/23634147/d9ddbe42-02d9-11e7-92cf-9ed91d40f664.png)

**Comment by Dynalon** [comment] 2017-03-30 18:01
Not a bug, closing this.

**Closed by Dynalon** 2017-03-30 18:01 UTC
