### ISSUE TITLE
syntax highlighting hangs with unknown language

### ISSUE THREAD

**Issue by oliver-graetz** [Dynalon/mdwiki#191] opened 2015-02-09 16:41 UTC
When using Firefox (currently v35.0.1) then using the syntax highlighting hangs when MDwiki doesn't recognize the language. Example:

    # Problematic Markdown

    The following will make MDwiki turn Firefox unresponsive:

    ```unknownlanguage
        // some code
    ```

Firefox will become unresponsive. It might show the dialog asking to stop the script but it won't even respond when telling it to stop the script. The expected behaviour would be anything but this. For example, it might render it as regular verbatim text (like when using 4 spaces indent) and generate a console warning `syntax highlighting: unknown language "unknownlanguage" on line 5`.

**Comment by Dynalon** [comment] 2015-02-09 19:30
duplicate of #39

**Closed by Dynalon** 2015-02-09 19:30 UTC

**Comment by oliver-graetz** [comment] 2015-02-09 20:04
Whoops. Well, I didn't look in already CLOSED issues.
