### ISSUE TITLE
MDWIKI carsh if exist  misspelling after the backticks in the code block

### ISSUE THREAD

**Issue by nopyhe** [Dynalon/mdwiki#225] opened 2015-07-23 00:30 UTC
Like this

    ```python
    print("Hello world!")
    ```
run good.

Buf if there is a misspelling or a language unsupported like:

    ```pytho
    print("Hello world!")
    ```

    ```nginx
     [...]
    ```

MDWIKI crashed.

**Comment by Dynalon** [comment] 2015-07-23 05:01
duplicate of #39

**Closed by Dynalon** 2015-07-23 05:01 UTC
