### ISSUE TITLE
html and xml syntax highlighting make the browser tab crash

### ISSUE THREAD

**Issue by alinnert** [Dynalon/mdwiki#192] opened 2015-02-17 11:33 UTC
The site crashes when I use `html` and `xml` syntax highlighting like this:

    ```html
    <div>hello world</div>
    ```

This makes the browser tab crash completely. I can't even reload the page after I fix the problem; I have to close it and open a new one.
On the other side highlighting for `php` for example works fine.

**Comment by Dynalon** [comment] 2015-02-17 12:21
duplicate of #39

**Closed by Dynalon** 2015-02-17 12:21 UTC
