### ISSUE TITLE
JS freeze when use tag HTML for code

### ISSUE THREAD

**Issue by Darkitty** [Dynalon/mdwiki#231] opened 2015-08-21 09:45 UTC
Hi,

I have wrote some code in HTML and my browser freeze when use the HTML for this. That is my code :
```html
<img src="chemin/image" alt="nom_image" />
```
When I delete the tag, it's work great. The script block at line 118 :
```JS
var hljs=new function(){function l(o){return o.replace(/&/gm,"&amp;").replace(/</gm,"&lt;").replace(/>/gm,"&gt;")}function b(p){for(var o=p.firstChild;o;o=o.nextSibling){if(o.nodeName=="CODE"){return o}...
```

(I don't paste the entire line)

Thank

**Comment by Dynalon** [comment] 2016-01-21 20:55
duplicate of #39

**Closed by Dynalon** 2016-01-21 20:55 UTC
